### PR TITLE
Is this a noarch pkg?

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@dopplershift I just got here today and looking at this, it seemed like a noarch pkg. Could you please have a quick peek and let me know if this is accurate? THANKS!

**Comment by ngam** [comment]
(Previously, e.g. see #21, this was built for all combinations separately, 23 of them, which seemed like a waste...)

**Comment by dopplershift** [comment]
@ngam This seems like a good candidate for noarch based on upstream, and this PR seems to be making the switch fine.

**Review by dopplershift — APPROVED** [review]
@ngam This seems like a good candidate for noarch based on upstream, and this PR seems to be making the switch fine.

**Pull request merged**
