### PR TITLE
Add linux_ppc64le and linux_aarch64 builds

### PR DESCRIPTION
**Pull request by ksangeek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ksangeek** [comment]
Hi @CurtLH Do you have any idea on why the `linux_ppc64le` build is failing? I tried it on a Power machine and there it built fine!

**Comment by CurtLH** [comment]
I'm not sure what the issue is @ksangeek.  Any thoughts from @conda-forge/help-python?

**Comment by mariusvniekerk** [comment]
@CurtLH This is normal for ppc64le.  Sadly travisci runs on both .org and .com  The .com stuff just fails.

**Comment by ksangeek** [comment]
Thank you @mariusvniekerk for helping in here.

**Pull request merged**
